import os
import sys
import duckdb
import pandas as pd
import numpy as np


# Ensure AWS Region is set for Headless SSM
os.environ['AWS_DEFAULT_REGION'] = 'ap-south-1'

sys.path.append('/home/ec2-user/project-intelligent')
from src.utils.iceberg_manager import write_arrow_to_iceberg
from src.utils.audit import write_audit_record
from src.utils.alerts import publish_sns_alert

def main():
    date_str = os.environ.get('EXECUTION_DATE', pd.Timestamp.utcnow().strftime('%Y-%m-%d'))
    print(f"Starting J12 Feature Engineering for {date_str}")
    
    try:
        con = duckdb.connect()
        os.environ['HOME'] = '/tmp'
        con.execute("SET home_directory='/tmp';")
        con.execute("INSTALL avro; LOAD avro;")
        con.execute("INSTALL iceberg; LOAD iceberg;")
        con.execute("INSTALL aws; LOAD aws; CALL load_aws_credentials();")
        con.execute("SET s3_region='ap-south-1';")
        con.execute("SET unsafe_enable_version_guessing=true;")
        
        # Query the enriched OHLCV data from Silver
        query = """
        SELECT symbol, date, open, high, low, close, volume, market_context, delivery_pct
        FROM iceberg_scan('s3://project-intelligent-silver-307828758318/ohlcv_enriched', allow_moved_paths=true)
        ORDER BY symbol, date
        """
        
        print("Loading Silver data into memory for Feature Engineering...")
        df = con.execute(query).df()
        
        if df.empty:
            print("No data found to compute features.")
            sys.exit(0)
            
        print("Calculating Technical Indicators using pandas-ta...")
        
        # We need to sort and group by symbol to apply pandas-ta correctly without data leakage
        df = df.sort_values(by=['symbol', 'date'])
        
        features_list = []
        
        for symbol, group in df.groupby('symbol'):
            # Convert to standard types required by pandas-ta
            group['open'] = pd.to_numeric(group['open'])
            group['high'] = pd.to_numeric(group['high'])
            group['low'] = pd.to_numeric(group['low'])
            group['close'] = pd.to_numeric(group['close'])
            group['volume'] = pd.to_numeric(group['volume'])
            
            # Ensure index is datetime for some pandas-ta functions if necessary, but default index works
            
            import ta

            # Technical Indicators
            # RSI
            group['rsi_14'] = ta.momentum.RSIIndicator(close=group['close'], window=14).rsi()
            
            # MACD
            macd = ta.trend.MACD(close=group['close'], window_fast=12, window_slow=26, window_sign=9)
            group['macd_12_26_9'] = macd.macd()
            group['macdh_12_26_9'] = macd.macd_diff()
            group['macds_12_26_9'] = macd.macd_signal()
            
            # Bollinger Bands
            bb = ta.volatility.BollingerBands(close=group['close'], window=20, window_dev=2)
            group['bbl_20_2_0'] = bb.bollinger_lband()
            group['bbm_20_2_0'] = bb.bollinger_mavg()
            group['bbu_20_2_0'] = bb.bollinger_hband()
            
            # ATR
            atr = ta.volatility.AverageTrueRange(high=group['high'], low=group['low'], close=group['close'], window=14)
            group['atr_14'] = atr.average_true_range()
            
            # Returns
            group['return_1d'] = group['close'].pct_change(1)
            group['return_5d'] = group['close'].pct_change(5)
            group['return_21d'] = group['close'].pct_change(21)
            
            # Price proximity to 52-week (252 day) high
            group['high_52w'] = group['high'].rolling(window=252, min_periods=1).max()
            group['proximity_to_52w_high'] = group['close'] / group['high_52w']
            
            # Fill NAs generated by rolling windows with 0 for safety in ML (or drop them later)
            group = group.fillna(0)
            
            features_list.append(group)
            
        final_features_df = pd.concat(features_list, ignore_index=True)
        
        # Clean column names generated by pandas-ta to remove special characters
        final_features_df.columns = final_features_df.columns.str.replace(r'[^a-zA-Z0-9_]', '_', regex=True).str.lower()
        
        # Write to Gold Layer
        import pyarrow as pa
        arrow_table = pa.Table.from_pandas(final_features_df)
        
        table_name = "features"
        full_table_name = write_arrow_to_iceberg(table_name, arrow_table, namespace="project_intelligent_gold")
        
        print(f"Feature Engineering completed and written to {full_table_name}")
        write_audit_record("J12", date_str, "Success", len(final_features_df))
        
    except Exception as e:
        print(f"Failed to process Feature Engineering: {e}")
        write_audit_record("J12", date_str, "Failed", 0)
        publish_sns_alert("J12 Critical Failure", str(e))
        raise

if __name__ == "__main__":
    main()
